language: node_js
dist: trusty
addons:
  chrome: stable
node_js:
  - "5"
before_script:
  - npm install
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start +extension RANDR
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - npm run test:sl
env:
  global:
    - SAUCE_USERNAME=mipengine
    - SAUCE_ACCESS_KEY=fab3190e-a7d4-49eb-b082-f01dca94e07c
